In [1]:
import pandas as pd
import numpy as np

In [2]:
tt = pd.read_csv('../Data/commute_tt_results_v2.csv')
tt.head()

,geoid,ctlabel,boro_code,boro_name,ct2010,boro_ct2010,cdeligibil,ntacode,ntaname,puma,...,CBD13,CBD14,CBD15,CBD16,CBD17,CBD18,CBD19,CBD20,CBD21,CBD22
0,36061009800,98.0,1,Manhattan,9800,1009800,I,MN19,Turtle Bay-East Midtown,3808,...,21.0,28.0,22.0,23.0,27.0,25.0,15.0,19.0,13.0,38.0
1,36061010200,102.0,1,Manhattan,10200,1010200,I,MN17,Midtown-Midtown South,3807,...,24.0,23.0,19.0,20.0,27.0,22.0,22.0,19.0,17.0,38.0
2,36061010400,104.0,1,Manhattan,10400,1010400,I,MN17,Midtown-Midtown South,3807,...,23.0,29.0,17.0,21.0,28.0,22.0,27.0,22.0,17.0,39.0
3,36061011300,113.0,1,Manhattan,11300,1011300,I,MN17,Midtown-Midtown South,3807,...,16.0,19.0,11.0,15.0,18.0,19.0,18.0,21.0,16.0,43.0
4,36061013000,130.0,1,Manhattan,13000,1013000,I,MN40,Upper East Side-Carnegie Hill,3805,...,28.0,31.0,32.0,32.0,36.0,36.0,11.0,17.0,6.0,51.0

In [3]:
#column for mean 
tt['mean_to_cbd'] = tt.iloc[:, -22:].mean(axis=1)

In [4]:
#travel time to the closest cbd
tt['closest_cbd'] = tt.iloc[:, -22:].min(axis=1)

In [5]:
#load cbd data 
cbd = pd.read_csv('../Data/NTA_CBD_final.csv')
cbd

,Unnamed: 0,ntacode,c000,area_km2,%_cbd_jobs,borocode,boroname,countyfips,ntaname,shape_area,shape_leng,geometry,Center_Lat,Center_Lon,jobs_km2
0,0,BK09,13119.0,0.161585,0.005953,3.0,Brooklyn,47,Brooklyn Heights-Cobble Hill,9.984670e+06,14253.675375,"POLYGON ((-73.99236367043254 40.689690123777, ...",40.695469,-73.994871,81189.237281
1,1,BK38,90452.0,0.336149,0.041043,3.0,Brooklyn,47,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2.846257e+07,32363.990305,POLYGON ((-73.97905767012286 40.70595288910062...,40.692921,-73.985990,269083.057942
2,2,BK68,9567.0,0.164809,0.004341,3.0,Brooklyn,47,Fort Greene,1.648290e+07,19828.474410,POLYGON ((-73.96939450111498 40.69608038942066...,40.690795,-73.974881,58048.886737
3,3,BK73,9870.0,0.194892,0.004479,3.0,Brooklyn,47,North Side-South Side,2.886841e+07,28145.428770,POLYGON ((-73.95814292441031 40.72440428440242...,40.714916,-73.958625,50643.372409
4,4,BX43,15124.0,0.248715,0.006863,2.0,Bronx,5,Norwood,1.570888e+07,22148.645113,"POLYGON ((-73.8830938237215 40.86660218502373,...",40.877138,-73.879022,60808.524894
5,5,MN09,31654.0,0.178083,0.014363,1.0,Manhattan,61,Morningside Heights,2.015832e+07,20744.313555,POLYGON ((-73.95210125149229 40.81144285350128...,40.807886,-73.962543,177749.060872
6,6,MN13,205454.0,1.554135,0.093225,1.0,Manhattan,61,Hudson Yards-Chelsea-Flatiron-Union Square,3.702973e+07,45454.722802,"POLYGON ((-74.00153309066991 40.7626445986302,...",40.747581,-73.999009,132198.259557
7,7,MN14,25866.0,0.350484,0.011737,1.0,Manhattan,61,Lincoln Square,1.580567e+07,19866.053195,POLYGON ((-73.97499744020551 40.77753254622205...,40.774847,-73.984699,73800.855164
8,8,MN15,41089.0,0.527848,0.018644,1.0,Manhattan,61,Clinton,1.838138e+07,35037.171580,"POLYGON ((-73.9938310813699 40.77293178785064,...",40.764175,-73.992397,77842.552727
9,9,MN17,794888.0,2.804878,0.360682,1.0,Manhattan,61,Midtown-Midtown South,3.019206e+07,27035.738130,POLYGON ((-73.97301487242227 40.76427887944538...,40.755733,-73.983503,283394.821528
10,10,MN19,183391.0,1.165173,0.083214,1.0,Manhattan,61,Turtle Bay-East Midtown,1.739787e+07,21638.781206,MULTIPOLYGON (((-73.96124698011525 40.74042359...,40.754307,-73.969018,157393.854483
11,11,MN20,132214.0,0.813655,0.059992,1.0,Manhattan,61,Murray Hill-Kips Bay,1.446585e+07,23134.268048,MULTIPOLYGON (((-73.96230391870563 40.73311366...,40.744211,-73.977500,162493.871540
12,12,MN21,29070.0,0.341109,0.013191,1.0,Manhattan,61,Gramercy,7.531455e+06,12091.587932,POLYGON ((-73.97849845639811 40.73679095652548...,40.736824,-73.984051,85222.116780
13,13,MN22,6247.0,0.086439,0.002835,1.0,Manhattan,61,East Village,1.089549e+07,13539.197632,POLYGON ((-73.98255629297823 40.73135013405204...,40.727620,-73.985938,72270.834138
14,14,MN23,56353.0,0.744786,0.025570,1.0,Manhattan,61,West Village,2.500053e+07,29385.030625,POLYGON ((-73.98990295970057 40.73443479013692...,40.733055,-74.001562,75663.323807
15,15,MN24,198999.0,2.325628,0.090296,1.0,Manhattan,61,SoHo-TriBeCa-Civic Center-Little Italy,2.485957e+07,24284.700443,POLYGON ((-73.99260322198447 40.72413644968342...,40.720767,-74.004678,85567.855776
16,16,MN25,238765.0,1.549032,0.108340,1.0,Manhattan,61,Battery Park City-Lower Manhattan,1.905626e+07,45700.005462,MULTIPOLYGON (((-74.00078295275682 40.69428651...,40.708002,-74.010235,154138.228213
17,17,MN27,21575.0,0.279730,0.009790,1.0,Manhattan,61,Chinatown,1.450195e+07,20788.888972,POLYGON ((-73.98382387298197 40.72147287206694...,40.715607,-73.994630,77127.903206
18,18,MN31,40212.0,0.368367,0.018246,1.0,Manhattan,61,Lenox Hill-Roosevelt Island,2.150156e+07,37708.444332,MULTIPOLYGON (((-73.94180032729433 40.76904692...,40.764965,-73.955091,109162.999455
19,19,MN33,24574.0,0.199925,0.011151,1.0,Manhattan,61,East Harlem South,1.665074e+07,18625.042699,POLYGON ((-73.93505300005583 40.79168720290905...,40.790011,-73.945751,122915.908020
20,20,MN40,20057.0,0.197350,0.009101,1.0,Manhattan,61,Upper East Side-Carnegie Hill,2.006533e+07,23778.406402,POLYGON ((-73.94933170560962 40.78519312655764...,40.774729,-73.961175,101631.872882
21,21,QN22,15307.0,0.304418,0.006946,4.0,Queens,81,Flushing,3.786484e+07,38363.970007,POLYGON ((-73.82331286855246 40.77957865983406...,40.761092,-73.828865,50282.788698

In [6]:
#multiply %job, mean, min, and original value(?)
for i in range(22):
    tt['w_tt_{}'.format(i+1)] = tt.loc[:, 'CBD{}'.format(i+1)]*cbd['%_cbd_jobs'][i]*tt['closest_cbd']*tt['mean_to_cbd']
tt

,geoid,ctlabel,boro_code,boro_name,ct2010,boro_ct2010,cdeligibil,ntacode,ntaname,puma,...,w_tt_13,w_tt_14,w_tt_15,w_tt_16,w_tt_17,w_tt_18,w_tt_19,w_tt_20,w_tt_21,w_tt_22
0,36061009800,98.0,1,Manhattan,9800,1009800,I,MN19,Turtle Bay-East Midtown,3808,...,21.115106,6.050043,42.881371,158.309753,222.978695,18.656052,20.862958,16.149475,9.018582,20.118825
1,36061010200,102.0,1,Manhattan,10200,1010200,I,MN17,Midtown-Midtown South,3807,...,77.704454,16.002542,119.250520,443.272233,717.999377,52.864378,98.529889,52.001886,37.975590,64.783337
2,36061010400,104.0,1,Manhattan,10400,1010400,I,MN17,Midtown-Midtown South,3807,...,91.180421,24.705761,130.645569,569.900335,911.711472,64.729493,148.063551,73.727118,46.499001,81.411061
3,36061011300,113.0,1,Manhattan,11300,1011300,I,MN17,Midtown-Midtown South,3807,...,29.345423,7.488597,39.109754,188.329134,271.155567,25.863051,45.667111,32.558958,20.247029,41.527319
4,36061013000,130.0,1,Manhattan,13000,1013000,I,MN40,Upper East Side-Carnegie Hill,3805,...,70.005957,16.655786,155.095413,547.687471,739.273432,66.801350,38.043485,35.929958,10.350210,67.141678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2036,36005007300,73.0,2,Bronx,7300,2007300,E,BX34,Melrose South-Mott Haven North,3710,...,740.350768,162.344631,1171.584053,4861.218827,5956.735571,571.896449,919.612296,319.309825,312.740156,564.865240
2037,36005005100,51.0,2,Bronx,5100,2005100,I,BX39,Mott Haven-Port Morris,3710,...,313.364794,71.081695,624.340396,2562.253058,2859.784624,316.555275,433.471796,125.091398,138.132694,270.423709
2038,36005006300,63.0,2,Bronx,6300,2006300,I,BX63,West Concourse,3708,...,751.038727,171.920258,1202.707741,4358.880568,6839.121349,521.049194,1038.898153,400.251825,360.475225,576.002480
2039,36081001900,19.0,4,Queens,1900,4001900,I,QN31,Hunters Point-Sunnyside-West Maspeth,4109,...,131.156244,31.567012,254.250011,933.744751,1378.873975,109.021654,195.940120,106.436608,65.154199,93.923211
2040,36081017100,171.0,4,Queens,17100,4017100,I,QN31,Hunters Point-Sunnyside-West Maspeth,4109,...,539.614262,130.455507,941.451471,3601.586897,5096.909157,410.499902,746.438552,410.541204,279.232282,262.827136

In [7]:
tt.columns

Index(['geoid', 'ctlabel', 'boro_code', 'boro_name', 'ct2010', 'boro_ct2010',
       'cdeligibil', 'ntacode', 'ntaname', 'puma', 'shape_leng', 'shape_area',
       'geometry', 'Bus_Access', 'Subway_Access', 'Bus_Count', 'Subway_Count',
       'Center_Lat', 'Center_Lon', 'area_km2', 'formatted', 'CBD1', 'CBD2',
       'CBD3', 'CBD4', 'CBD5', 'CBD6', 'CBD7', 'CBD8', 'CBD9', 'CBD10',
       'CBD11', 'CBD12', 'CBD13', 'CBD14', 'CBD15', 'CBD16', 'CBD17', 'CBD18',
       'CBD19', 'CBD20', 'CBD21', 'CBD22', 'mean_to_cbd', 'closest_cbd',
       'w_tt_1', 'w_tt_2', 'w_tt_3', 'w_tt_4', 'w_tt_5', 'w_tt_6', 'w_tt_7',
       'w_tt_8', 'w_tt_9', 'w_tt_10', 'w_tt_11', 'w_tt_12', 'w_tt_13',
       'w_tt_14', 'w_tt_15', 'w_tt_16', 'w_tt_17', 'w_tt_18', 'w_tt_19',
       'w_tt_20', 'w_tt_21', 'w_tt_22'],
      dtype='object')

In [9]:
tt.to_csv('../Data/weighted_tt.csv')